Add Swagger docs at "/"
eigenkarmanetwork/EKN pull request #36
Opened 2023-02-28 07:51 UTC by mruwnik

2023-02-28 08:04 UTC, mruwnik reviewed
I chmoded start.sh to be executable, which is why it's changed, but the contents aren't

2023-02-28 08:04 UTC, mruwnik commented on requirements.txt
> +flask-swagger==0.2.14
it's good practice to have specific versions provided, to avoid bugs that stem from weird version mismatches

2023-03-01 14:28 UTC, tayler6000 commented on ekn/routes/registration.py
> +            application/xml:
No, but we would need to update the website front end if we want to change it.

2023-03-01 14:35 UTC, tayler6000 requested changes

2023-03-01 14:35 UTC, tayler6000 commented on requirements.txt
> +flask-swagger==0.2.14
Generally, it's better to have dependents not pinned so that way systems will automatically pull updates/patches.  If you pin these requirements and a user tries to install something else in the same environment that requires, let's say numpy 1.24.1, pip would give them an error when our code would most likely work fine with numpy 1.24.1.

2023-03-01 14:35 UTC, tayler6000 commented on requirements.txt
> +flask-swagger==0.2.14
Please remove the version numbers, then approved.

2023-03-01 14:36 UTC, tayler6000 commented
> I chmoded start.sh to be executable, which is why it's changed, but the contents aren't

Oh, ok I was about to ask.

2023-03-04 03:48 UTC, tayler6000 approved these changes

2023-03-04 03:49 UTC, merged